### ISSUE TITLE
Unresolved import using crate instruction

### ISSUE THREAD

**Issue by misterblonde** [blockchainlover2019/solana-escrow#1]
Hi, 
I tried to use your code, but it doesn't compile. No matter what I try, the code does not  compile. 

```
 Compiling bpf-program-template v0.1.0 (/Users/julia/Desktop/rustTut/solana-escrow)
error[E0432]: unresolved import `crate::instruction`
  --> src/processor.rs:12:14
   |
12 | use crate::{ instruction::EscrowInstruction, error::EscrowError, state::Escrow };
   |              ^^^^^^^^^^^
   |              |
   |              unresolved import
   |              help: a similar path exists: `solana_program::instruction`
```

**Comment by blockchainlover2019** [comment]
Sorry. the codes were not up-to-date.
I fixed all bugs. And I'd like to let you know that these codes are from https://paulx.dev/blog/2021/01/14/programming-on-solana-an-introduction/
Paul is one of core-devs of project-serum/anchor and his blog is the best material for solana newbies.
I want you to start from his blog for solana journey. Good Luck!
